import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import React from "react"
import TaskLists from "../components/TaskLists"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TaskLists/>
    </React.Fragment>
  )
}

export default Home
